### ISSUE TITLE
accessing text fields from form-data not working right

### ISSUE THREAD

**Issue by therealokoro** [wobsoriano/h3-formidable#1]
Hello @wobsoriano .

Glad to see you once again building something that is always useful 🙂.

But I noticed when you try to use the `readBody` method from `h3` to access other text fields from the form-data, it gives a whole lot of gibberish which isn't useful. This is not so surprising, because when you send data using the `FormData` interface, the encoding is different.

Now my question is, how do we now access data in other fields.

**Comment by wobsoriano** [comment]
Thanks, @therealokoro!

What about [readRawBody](https://github.com/unjs/h3/blob/main/src/utils/body.ts#L18)?

**Comment by wobsoriano** [comment]
Should be able to access the fields now

```ts
export default eventHandler(async (event) => {
  // only files
  const files = await readFiles(event)

  // with fields
  const { fields, files } = await readFiles(event, {
    includeFields: true,
    // other formidable options here
  })
})
```

https://github.com/wobsoriano/h3-formidable/releases/tag/v0.2.2

**Comment by therealokoro** [comment]
Nice work @wobsoriano. But things doesn't seem to working as expected yet, sadly.

So here's my code.

```js
// new form data instance
const formData = new FormData()

// append data to it
formData.append("name", "Some name")
formData.append("shortname", "very short")
formData.append("file", file) // assume the variable holds a file

// make request
const res = await $fetch("/api/new", {
    method: "POST",
    body: formData
})
```

Now on the server I have the following

```ts
export default defineEventHandler(async (event) => {
	try {
		// check if user is a super admin
		await checkUserRole(event, "Super")

		const { fields, files } = await readFiles(event, {
			keepExtensions: true,
			filename(name, ext, part, form) {
				console.log(name, ext) // this never gets called
				form.on("field", (name, value) => {
					console.log({ name, value }) // neither does this get called
				})
				return `${Date.now()}`
			},
			uploadDir: "./server/uploads/",
			includeFields: true
		})

		const input = SomeZodSchema.parse(fields)

		if (input) {
			return {
				error: false,
				message: null,
				data: fields
			}
		}
	} catch (e: any) {
		return { error: true, message: handleErrors(e), data: null }
	}
})

```

Now say the code doesn't catch any error this is the output I get

```
fields: {
    name: [ 'Some name' ],
    shortname: [ 'very short' ],
    file: ...
  }
```

Notice that each field is placed in an array which i have absolutely no idea why. 
This is what is expected

```
fields: {
    name: 'Some name',
    shortname: 'very short',
    file: ...
  }
```

And may I add that this happens only when the form contains the `FormData`

**Comment by therealokoro** [comment]
Still having this issue @wobsoriano
