### ISSUE TITLE
lack of documentation

### ISSUE THREAD

**Issue by NyllRE** [wobsoriano/h3-formidable#2]
I wanted to look at an example of a working project using this package, maybe some more explaination on how to implement with nuxt or something and I found nothing. Honestly I believe this will limit adoption of this package even though it's really useful for nitro or h3 users and I don't see quite a close matchup for this library but I just don't know how to use it, how to send the data from the frontend etc. I will be doing the usual trial and error until I figure it out but I think a simple [docus](https://docus.dev) documentation page would do the trick

**Comment by wobsoriano** [comment]
I think docus would be overkill. What do you think is missing?

**Comment by wobsoriano** [comment]
Updated docs.

**Comment by NyllRE** [comment]
> What do you think is missing?

I mean anything more than just a code snippet, at least a codesandbox/stackblitz minimal example project. I tried working with it blindly for an hour and just reverted to creating everything manually

**Comment by wobsoriano** [comment]
https://stackblitz.com/edit/nuxt-starter-ykuwmn?file=app.vue
