### ISSUE TITLE
TypeScript Shim not working

### ISSUE THREAD

**Issue by baboon-king** [wobsoriano/h3-formidable#3]
TypeScript Shim not working

https://github.com/wobsoriano/h3-formidable#typescript-shim

then

I added `export {};`

like that image
![image](https://github.com/wobsoriano/h3-formidable/assets/63645337/4dcae7ce-5a18-46c3-bc8d-5e0a9c838274)

**Comment by wobsoriano** [comment]
Should be fixed in https://github.com/wobsoriano/h3-formidable/commit/d187a6d597305e2e61978c62dffc328573e017d4

Please reopen if not!
