### ISSUE TITLE
readFiles no result 

### ISSUE THREAD

**Issue by AuYuHui** [wobsoriano/h3-formidable#6]
https://stackblitz.com/edit/nuxt-starter-x9wy3k?file=server%2Fapi%2Fupload.ts

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/h3-formidable#usage-with-nuxt

If you want to use `readFiles`, you need to ditch server middleware. Any uploaded file will be available in `event.context.files` if you use a server middleware.
