### ISSUE TITLE
Add ability to use formidable helpers

### ISSUE THREAD

**Issue by genu** [wobsoriano/h3-formidable#9]
Newer version of formidable added [Helpers](https://github.com/node-formidable/formidable#helpers)

It would be great to be able to use them when parsing a form.

A typical use case for this is to use the `firstValues`, since the default behavior in formidable is to parse everything as an array

**Comment by wobsoriano** [comment]
Hi! Please update to v1 to use the helpers - https://github.com/wobsoriano/h3-formidable#helpers

There is a breaking change btw - https://github.com/wobsoriano/h3-formidable/pull/11
